config/routes.rb
Rails.application.routes.draw do
  root to: 'applications#index'
  devise_for :users
  resources :applications do
    resources :gemfiles, only: [:index, :new, :create, :edit, :update, :show]
    resources :models do
      resources :columns, only: [:new, :create, :edit, :update, :destroy] do
        resources :options, only: [:new, :create]
      end
    end
    resources :app_controllers do
      resources :app_actions, only: [:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/controllers/app_controllers_controller.rb
class AppControllersController < ApplicationController
  before_action :app_controller_form_variable, only: [:new, :edit]
  before_action :find_app_controller, only: [:edit, :update, :destroy, :show]

  def index
    @application = Application.find(params[:application_id])
    @app_controllers = @application.app_controllers
  end

  def new
    app_controller_form_variable
    @app_controller = AppController.new
  end

  def create
    @app_controller = AppController.new(app_controller_params)
    if @app_controller.save
      SetDefaultActionService.set(@app_controller)
      redirect_to application_app_controller_app_actions_path(app_controller_id: @app_controller)
    else
      app_controller_form_variable
      render :new
    end
  end

  def edit
  end

  def update
    if @app_controller.update(app_controller_params)
      redirect_to application_app_controllers_path
    else
      app_controller_form_variable
      render :edit
    end
  end

  def destroy
    @app_controller.destroy
    redirect_to application_app_controllers_path
  end

  def show
    @gemfile = Gemfile.find_by(application_id: params[:application_id])
    @app_controllers = AppController.where(application_id: params[:application_id])
    @app_actions = AppAction.where(app_controller_id: params[:id])
  end

  private

  def app_controller_form_variable
    @application = Application.find(params[:application_id])
    @models = @application.models
    @app_controllers = @application.app_controllers
  end

  def app_controller_params
    params.require(:app_controller).permit(
      :name, :parent, :index_select, :new_select, :create_select, :edit_select, :update_select, :destroy_select, :show_select
    ).merge(application_id: params[:application_id])
  end

  def find_app_controller
    @app_controller = AppController.find(params[:id])
  end
end

app/helpers/app_controllers_helper.rb
module AppControllersHelper
  # shared/controllerの部分テンプレートに使用しているメソッドは、app_actions_helper.rbに記載
end

app/views/app_controllers/_normal_form.html.erb
<%= form_with(model: [@application, @app_controller], local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  
  <div class="field">
    <%= f.label :name, '対象モデル' %>
    <%= f.collection_select(:name, @models, :name, :name) %>
  </div>
  <p>
    ルーティングのネスト構造で、親の関係になるコントローラーを選択してください。<br>
    親のコントローラーが存在しない場合は未選択のまま進めてください。
  </p>
  <div class="field">
    <%= f.label :parent, '親コントローラー名' %>
    <%= f.collection_select(:parent, @app_controllers, :name, :name, include_blank: true) %>
  </div>  
  <br>
  <div class="field">
    <div class="info">
      それぞれのアクションを使用するのか、またログインユーザーに限定するのかを選択してください
    </div>
    <div class="flex-contents">
      <div class="index">
        <h5><%= f.label :index_select, 'index' %></h5>
        <%= f.radio_button :index_select, 1 %>アクションなし<br>
        <%= f.radio_button :index_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :index_select, 3 %>ログインユーザーのみ<br>
      </div>
      <div class="new">
        <h5><%= f.label :new_select, 'new' %></h5>
        <%= f.radio_button :new_select, 1 %>アクションなし<br>
        <%= f.radio_button :new_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :new_select, 3 %>ログインユーザーのみ<br>
      </div>
      <div class="create">
        <h5><%= f.label :create_select, 'create' %></h5>
        <%= f.radio_button :create_select, 1 %>アクションなし<br>
        <%= f.radio_button :create_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :create_select, 3 %>ログインユーザーのみ<br>
      </div>
    </div>
    <div class="flex-contents">
      <div class="edit">
        <h5><%= f.label :edit_select, 'edit' %></h5>
        <%= f.radio_button :edit_select, 1 %>アクションなし<br>
        <%= f.radio_button :edit_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :edit_select, 3 %>ログインユーザーのみ<br>
      </div>
      <div class="update">
        <h5><%= f.label :update_select, 'update' %></h5>
        <%= f.radio_button :update_select, 1 %>アクションなし<br>
        <%= f.radio_button :update_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :update_select, 3 %>ログインユーザーのみ<br>
      </div>
      <div class="destroy">
        <h5><%= f.label :destroy_select, 'destroy' %></h5>
        <%= f.radio_button :destroy_select, 1 %>アクションなし<br>
        <%= f.radio_button :destroy_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :destroy_select, 3 %>ログインユーザーのみ<br>
      </div>
      <div class="show">
        <h5><%= f.label :show_select, 'show' %></h5>
        <%= f.radio_button :show_select, 1 %>アクションなし<br>
        <%= f.radio_button :show_select, 2, checked: true %>アクションあり<br>
        <%= f.radio_button :show_select, 3 %>ログインユーザーのみ<br>
      </div>
    </div>
  <br>
  <div class="actions">
    <%= f.submit "各アクションの設定へ" %>
  </div>
<% end %>

app/views/app_controllers/edit.html.erb
<h1><%= @app_controller.name %>コントローラーの編集</h1>
<%= render partial: "normal_form" %>

<%= render partial: "shared/link_index" %>

app/views/app_controllers/index.html.erb
<h1><%= @application.name %>のコントローラー一覧</h1>
<div>
  <% if @app_controllers.length == 0 %>
    コントローラーはまだ登録されていません。
  <% else %>
    <% @app_controllers.each do |app_controller| %>
      <div>
        <%= app_controller.name %>コントローラー<br>
        <%= link_to '編集へ', edit_application_app_controller_path(id: app_controller) %>
        <%= link_to '削除', application_app_controller_path(id: app_controller), method: :delete %>
        <%= link_to 'コード表示', application_app_controller_path(id: app_controller) %><br>
        <%= link_to 'アクション一覧へ', application_app_controller_app_actions_path(app_controller_id: app_controller) %>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<%= link_to 'コントローラー作成へ', new_application_app_controller_path %><br>
<%= render partial: "shared/link_index" %>

app/views/app_controllers/new.html.erb
<h1>新規コントローラー作成</h1>
<p>
  関連するモデル名をからコントローラー名を作成します。<br>
  モデルと関連しないコントローラー名を作成する場合、下のフォームから作成してください。
</p>
<%= render partial: "normal_form" %>

<%= render partial: "shared/link_index" %>

app/views/app_controllers/show.html.erb
<h2><%= @app_controller.name.tableize %>コントローラーの作成と編集</h2>

<div class="terminal-field">
  <div class="terminal-header">
    <div class="terminal-icons">
      <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
    </div>
    <div class="terminal-title">
      ターミナル：関連ファイルの作成
    </div>
  </div>
  <div class="terminal-contents">
    rails g controller <%= @app_controller.name.tableize %>
  </div>
</div>
<div class="terminal-field">
  <div class="terminal-header">
    <div class="terminal-icons">
      <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
    </div>
    <div class="terminal-title">
      ターミナル：対象ファイルへジャンプ
    </div>
  </div>
  <div class="terminal-contents">
    code app/controllers/<%= @app_controller.name.tableize %>_controller.rb<br>
  </div>
</div>

<h2><%= @app_controller.name.tableize %>コントローラーの編集</h2>

<%# 部分テンプレートを使用し、コントローラーのコードを表示します。また編集削除のリンクは表示されません。 %>
<%= render partial: "shared/controller", locals: {links: false} %>
<p>
  redirect_toの行き先はroot_pathになっています。<br>
  また自動生成されたメソッドなどに不要なものがあれば、削除をお願いします。
</p>

<% if @gemfile.rubocop %>
  <div class="terminal-field">
    <div class="terminal-header">
      <div class="terminal-icons">
        <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
      </div>
      <div class="terminal-title">
        ターミナル：Rubocopの実行
      </div>
    </div>
    <div class="terminal-contents">
      bundle exec rubocop -a
    </div>
  </div>
<% end %>

<%= render partial: "shared/link_index" %>