config/routes.rb
Rails.application.routes.draw do
  root to: 'applications#index'
  devise_for :users
  resources :applications do
    resources :gemfiles, only: [:index, :new, :create, :edit, :update, :show]
    resources :models do
      resources :columns, only: [:new, :create, :edit, :update, :destroy] do
        resources :options, only: [:new, :create]
      end
    end
    resources :app_controllers do
      resources :app_actions, only: [:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/application.rb
class Application < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_one :gemfile, dependent: :destroy
  has_many :models, dependent: :destroy
  has_many :columns, dependent: :destroy
  has_many :app_controllers, dependent: :destroy
  has_many :app_actions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :find_application, only: [:edit, :update, :destroy, :show]

  def index
    @applications = Application.where(user_id: current_user.id)
  end

  def new
    @application = Application.new
  end

  def create
    @application = Application.new(application_params)
    if @application.save
      redirect_to new_application_gemfile_path(@application.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @application.update(application_params)
      redirect_to edit_application_gemfile_path(@application.id)
    else
      render :edit
    end
  end

  def destroy
    @application.destroy
    redirect_to root_path
  end

  def show
    @models = @application.models
    @app_controllers = @application.app_controllers
  end

  private

  def application_params
    params.require(:application).permit(:name, :description).merge(user_id: current_user.id)
  end

  def find_application
    @application = Application.find(params[:id])
    redirect_to root_path if current_user.id != @application.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 半角スペースを指定した回数だけ挿入するメソッド
  def insert_space(roops)
    space = ''
    if roops >= 1
      roops.times do
        space += '&nbsp;'
      end
    end
    raw(space)
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/edit.html.erb
<h1>アプリケーション更新</h1>

<%= form_with model: @application, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, autofocus: true %>
  </div>
  
  <div class="actions">
    <%= f.submit "更新" %>
  </div>
<% end %>

<%= link_to 'アプリケーション一覧へ戻る', root_path %>

app/views/applications/index.html.erb
<%= "#{current_user.nickname}さんがログイン中" %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<%= link_to 'ユーザー編集', edit_user_registration_path, method: :get %>
<br>

<div class="flex-contents">
  <%# 左側: アプリケーション一覧 %>
  <div class="application-index">
    <h1>アプリケーション一覧</h1>
    <%= link_to 'アプリケーション新規作成へ', new_application_path %>
    <% if @applications != nil %>
      <div>
        <% @applications.each do |application| %>
          <div class="application-name">
          <%= application.name %>
          </div>
          <div class="application-description">
          <%= application.description %>
          </div>
          <%= link_to '編集画面へ', edit_application_path(application) %>
          <br>
          <%= link_to '削除', application_path(application), method: :delete %>
          <br>
          <%= link_to '詳細設定へ', application_path(application) %>
          <br>
        <% end %>
      </div>
    <% else %>
      <div>
        <p>まだアプリケーションが作成されていません</p>
      </div>
    <% end %>
  </div>

  <%# 右側: アプリケーションに関する説明 %>
  <div class="service-explain">
    <div class="greeting">
      <div class="greeting-title">
        <h1>ご挨拶</h1>
      </div>
      <div class="greeting-contents">
        <h3>
          当アプリケーションは、<br>
          <span>Ruby on Rails の制作補助アプリです。</span><br>
        </h3>
        <h3>
          これから作成したいアプリケーションの情報を登録していただくと、<br>
          登録内容をもとに記載するコードを自動で作成し、表示します。
        </h3>
        <h3>
          当アプリの最大の目的は、アプリケーションの骨組みを短時間で作成するとともに、<br>
          作業の抜け落ちや記入ミスを防ぐことにあります。
        </h3>
        <h3>
          皆様のアプリ開発の潤滑剤になれば幸いです。
        </h3>
      </div>
    </div>
    <div class="usage">
      <div class="usage-title">
        <h1>当サービスの使い方</h1>
      </div>
      <h3>ターミナルに関する操作</h3>
      <div class="display-field">
        <div class="terminal-field">
          <div class="terminal-header">
            <div class="terminal-icons">
              <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
            </div>
            <div class="terminal-title">
              ターミナル：操作の目的
            </div>
          </div>
          <div class="terminal-contents">
            ターミナルに記入するコード
          </div>
        </div>
      </div>
      <div class="usage-description">
        <h3>
          上記はターミナルを操作に関するコードが表示されます。<br>
          そのままコピー＆ペーストが可能な場合と、1行ずつ操作する場合などがあります。<br>
          必要に応じ注意書きを記載しておりますので、指示の通りに操作をお願いします。
        </h3>
      </div>
      <div class="display-field">
        <div class="code-field">
          <div class="code-tab">
            <%= image_tag "ruby_icon.png", class: "code-icon", size: "16x16", alt: "Ruby" %>
            ファイル名
            <%= image_tag "cross_icon.png", class: "code-icon", size: "16x16", alt: "close" %>
          </div>
          <div class="code-route">
            app > models > 
            <%= image_tag "ruby_icon.png", class: "code-icon", size: "12x12", alt: "Ruby" %>
            ファイル名
          </div>
          <div class="code-contents">
            コード内容
          </div>
        </div>
      </div>
      <div class="usage-description">
        <h3>
          上記はファイルに記載するコードが表示されます。<br>
          ほとんどの場合で、コピー＆ペーストが可能となっています。<br>
          内容が不十分な場合もあります。内容を確認し、必要に応じて加筆修正をお願いします。
        </h3>
      </div>
      <div class="usage-description">
        <h3>
          本アプリケーションは開発段階にあります。<br>
          作成したコードに問題が生じる場合もあります。<br>
          内容を確認しつつ、実装を進めてください。
        </h3>
      </div>
      
    </div>
  </div>
</div>

app/views/applications/new.html.erb
<h1>アプリケーション作成</h1>

<%= form_with model: @application, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, autofocus: true %>
  </div>
  
  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>

<%= link_to 'アプリケーション一覧へ戻る', root_path %>

app/views/applications/show.html.erb
<div>
  <h1><%= @application.name %></h1>
</div>

<div class="gemfile-index">
  <h3>使用Gem一覧</h3>
  <% if @application.gemfile != nil %>
    <% if @application.gemfile.devise %><p>devise</p><% end %>
    <% if @application.gemfile.pry_rails %><p>pry_rails</p><% end %>
    <% if @application.gemfile.image_magick %><p>image_magick</p><% end %>
    <% if @application.gemfile.active_hash %><p>active_hash</p><% end %>
    <% if @application.gemfile.rails_i18n %><p>rails_i18n</p><% end %>
    <% if @application.gemfile.ransack %><p>ransack</p><% end %>
    <% if @application.gemfile.rubocop %><p>rubocop</p><% end %>
    <% if @application.gemfile.rspec %><p>rspec</p><% end %>
    <% if @application.gemfile.payjp %><p>payjp</p><% end %>
    <% if @application.gemfile.s3 %><p>s3</p><% end %>
  <% else %>
    <p>Gemfileが登録されていません。</p>
    <p><%= link_to 'こちらから登録をお願いします。', new_application_gemfile_path(@application.id) %></p>
  <% end %>
</div>
<h2>
  各種登録データの確認/登録
</h2>
<div>
  <%= link_to 'モデル一覧へ', application_models_path(@application) %><br>
  <%= link_to 'コントローラー一覧へ', application_app_controllers_path(@application) %><br>
  <%= link_to 'アプリケーション一覧へ戻る', root_path %>
</div>

<div>
  <div>
    <h2>コード表示</h2>
      必要な情報を登録できたら、以下のリンクからアプリケーションの実装を進めてください。
    <h3>事前準備</h3>
    <%= link_to '事前準備1 雛形の作成など', application_gemfiles_path(@application) %><br>
    <%= link_to '事前準備2 README ルーティングなど', application_gemfile_path(@application)%>
  </div>
  <div class="flex-contents">
    <div class="model-codes">
      <h3>モデルに関するコード</h3>
      <% @models.each do |model| %>
        <%= link_to model.name, application_model_path(application_id: params[:id], id: model), class: link_to %><br>
      <% end %>
    </div>
    <div class="controller-codes">
      <h3>コントローラーに関するコード</h3>
      <% @app_controllers.each do |app_controller| %>
        <%= link_to app_controller.name, application_app_controller_path(application_id: params[:id], id: app_controller), class: link_to %><br>
      <% end %>
    </div>
  </div>
  <br>
  <h3>Herokuへのデプロイ</h3>
  <p>Herokuへデプロイを行う場合、以下の操作をしてください。</p>
  <%# ターミナル操作: アップロード %>
  <div class="terminal-field">
    <div class="terminal-header">
      <div class="terminal-icons">
        <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
      </div>
      <div class="terminal-title">
        ターミナル：アップロード
      </div>
    </div>
    <div class="terminal-contents">
      git push heroku master
    </div>
  </div>
  <%# ターミナル操作: アップロード %>
  <div class="terminal-field">
    <div class="terminal-header">
      <div class="terminal-icons">
        <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
      </div>
      <div class="terminal-title">
        ターミナル：Herokuのマイグレート
      </div>
    </div>
    <div class="terminal-contents">
      heroku run rails db:migrate
    </div>
  </div>
  <%# ターミナル操作: エラーログの確認 %>
  <div class="terminal-field">
    <div class="terminal-header">
      <div class="terminal-icons">
        <span class="close">●</span><span class="minimum">●</span><span class="fullscreen">●</span>
      </div>
      <div class="terminal-title">
        ターミナル：エラーログの確認
      </div>
    </div>
    <div class="terminal-contents">
      heroku logs --tail --app 
    </div>
  </div>
</div>

<p>
  以上でアプリケーション作成補助は終了となります。
</p>
<div>
  <%= link_to 'モデル一覧へ', application_models_path(@application) %><br>
  <%= link_to 'コントローラー一覧へ', application_app_controllers_path(@application) %><br>
  <%= link_to 'アプリケーション一覧へ戻る', root_path %>
</div>