config/routes.rb
Rails.application.routes.draw do
  root to: 'applications#index'
  devise_for :users
  resources :applications do
    resources :gemfiles, only: [:index, :new, :create, :edit, :update, :show]
    resources :models do
      resources :columns, only: [:new, :create, :edit, :update, :destroy] do
        resources :options, only: [:new, :create]
      end
    end
    resources :app_controllers do
      resources :app_actions, only: [:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/controllers/app_actions_controller.rb
class AppActionsController < ApplicationController
  before_action :find_app_action, only: [:edit, :update, :destroy]
  before_action :app_action_form_variable, only: [:new, :edit]

  def index
    @app_controller = AppController.find(params[:app_controller_id])
    @app_controllers = AppController.where(application_id: params[:application_id])
    @app_actions = @app_controller.app_actions
  end

  def new
    @app_action = AppAction.new
  end

  def create
    @app_action = AppAction.new(app_action_params)
    if @app_action.save
      redirect_to application_app_controller_app_actions_path
    else
      app_action_form_variable
      render :new
    end
  end

  def edit
  end

  def update
    if @app_action.update(app_action_params)
      redirect_to application_app_controller_app_actions_path
    else
      app_action_form_variable
      render :edit
    end
  end

  def destroy
    @app_action.destroy
    redirect_to application_app_controller_app_actions_path
  end

  private

  def app_action_params
    params.require(:app_action).permit(:target, :input1, :input2, :input3, :action_select, :action_code_id).merge(
      application_id: params[:application_id], app_controller_id: params[:app_controller_id]
    )
  end

  def find_app_action
    @app_action = AppAction.find(params[:id])
  end

  def app_action_form_variable
    @app_controller = AppController.includes(:app_actions).find(params[:app_controller_id])
    @application = @app_controller.application
    @models = @application.models.where(model_type_id: [1, 3, 5])
  end
end

app/helpers/app_actions_helper.rb
module AppActionsHelper
  # app_action#new/edit

  # アクション新規登録画面における、アクションタイプの選択肢を作成するメソッド
  def make_selects(app_controller)
    # 基本の７つのアクション
    seven_actions = %w[index new create edit update destroy show]
    # 共通する内容を登録するプライベートアクション
    common_actions = %w[common_variable1 common_variable2 common_variable3]
    selects = []
    targets = []
    array = {}
    seven_actions.each do |action|
      selects << [action.to_s, action.to_s] if app_controller["#{action}_select".to_sym] >= 2
    end
    common_actions.each do |action|
      selects << [action.to_s, action.to_s]
    end

    # フォーム専用のメソッドが作成されるされる対象とメソッド名
    app_controller.app_actions.each do |app_action|
      next unless app_action.action_code_id <= 8

      targets << app_action.target unless targets.include?(app_action.target)
      array[app_action.target.to_s.to_sym] = [] if array[app_action.target.to_s.to_sym].nil?
      unless array[app_action.target.to_s.to_sym].include?(app_action.action_select)
        array[app_action.target.to_s.to_sym] << app_action.action_select
      end
    end
    targets.each do |target|
      selects << ["#{target}_form_variable", "#{target}_form_variable"] if array[target.to_s.to_sym].length >= 2
    end

    selects
  end

  # app_action#index / _controller.html.erb

  # コントローラーのコード表示機能に関する内容
  ##  計画: contentsにハッシュ構造を持たせ、引数として使用することで複数のメソッドに渡って受け渡すことができるようにする。
  ### contentsのハッシュ一覧とその内容について
  ### contents[:各アクション名] -> app_actionを対象とするアクションごとに分配し格納する。ここから各アクション内のコードを作成する。
  ### contents[:params_targets] -> ストロングパラメーターを取得する必要のあるモデル名(string)を格納する。ここからmodel_paramsを作成する。
  ### contents[:form_targets] -> フォームの対象となるモデル名(string)を格納する。ここからmodel_form_variableを作成する
  ### contents[:モデル名_form_actions] -> model_form_variableを使用するアクションを格納する。ここからbefore_actionを作成する。
  ### contents[:model_form_variable] -> model_form_variableに実際に記載するインスタンス変数取得に関するコードを格納する。

  # コントローラーに登録されたアクションを配列に分配するメソッド
  def make_controller_array(app_actions)
    # contentsに必要なキーとそれに対応する空白の配列を作成する。
    contents = {}
    actions = %w[index new create edit update destroy show params_targets form_targets]
    actions.each do |action|
      contents[action.to_sym] = []
    end

    # コントローラーに登録されているアクションを配列に分配する。
    app_actions.each do |app_action|
      if app_action.action_code_id <= 96
        contents[app_action.action_select.to_s.to_sym] = [] if contents[app_action.action_select.to_s.to_sym].nil?

        contents[app_action.action_select.to_s.to_sym] << app_action

        # ストロングパラメーターを必要とするアクションから、対象となるモデル名を格納する
        if [2, 3, 4, 5, 6, 7, 8].include?(app_action.action_code_id) && !contents[:params_targets].include?(app_action.target)
          contents[:params_targets] << app_action.target
        end
        # formに関連するモデル名(string)と、model_form_variableを使用するアクションをそれぞれ格納する
        if app_action.action_code_id <= 8
          contents[:form_targets] << app_action.target unless contents[:form_targets].include?(app_action.target)

          contents["#{app_action.target}_form_actions".to_sym] = [] if contents["#{app_action.target}_form_actions".to_sym].nil?
          if app_action.action_code_id == 1 &&
             !contents["#{app_action.target}_form_actions".to_sym].include?(app_action.action_select)
            contents["#{app_action.target}_form_actions".to_sym] << app_action.action_select
          end
          if app_action.action_select == 'update' && !contents["#{app_action.target}_form_actions".to_sym].include?('edit')
            contents["#{app_action.target}_form_actions".to_sym] << 'edit'
          end
        end
      else # app_action.action_code_id >= 97 -> common_variableを使用するアクション
        sample = app_action.action_code.sample
        contents["#{sample}_targets".to_sym] = [] if contents["#{sample}_targets".to_sym].nil?
        contents["#{sample}_targets".to_sym] << app_action
      end
    end
    contents
  end

  # 基本の７つのアクションを対象に、登録内容に基づきコードを作成するメソッド。特殊なレイアウトのものにも対応している。
  def make_action_code_remake(app_action, links, content)
    case app_action.action_code_id
    when 5, 6, 7, 8 # 特殊なレイアウトを使用する場合
      create_action_template(app_action, content)
      content[:main] += "#{insert_space(6)}#{app_action.action_code.sample}" if links

      case app_action.action_code_id
      when 5, 6 # createのレイアウトの場合
        content[:first] += "#{insert_space(4)}@#{app_action.target} = "
        content[:first] += "#{app_action.target.classify}.new(#{app_action.target}_params)<br>"
      else # 7, 8 updateのレイアウトの場合
        content[:before] = content[:before].gsub(/save/, "update(#{app_action.target}_params)")
      end

      case app_action.action_code_id
      when 7
        content[:after] = content[:after].gsub(/:new/, ':edit')
      when 6, 8
        content[:before] = content[:before].gsub(/root_path/, input1.to_s) unless app_action.input1 == ''
        content[:after] = content[:after].gsub(/:new/, input2.to_s) unless app_action.input2 == ''
      end
    else # 特殊なレイアウトを使用しない場合
      code = insert_space(4)
      code += app_action.action_code.sample
      code = code.gsub(/models/, app_action.target.tableize.to_s)
      code = code.gsub(/model/, app_action.target.to_s)
      code = code.gsub(/Model/, app_action.target.classify.to_s)
      code = code.gsub(/条件式1/, app_action.input1.to_s) unless app_action.input1 == ''
      code = code.gsub(/条件式2/, app_action.input2.to_s) unless app_action.input2 == ''
      code = code.gsub(/条件式3/, app_action.input3.to_s) unless app_action.input3 == ''
      content[:main] = code
    end
  end

  # createに使用するレイアウトでHTMLを作成するメソッド
  def create_action_template(app_action, content)
    content[:before] += "#{insert_space(4)}if @#{app_action.target}.save<br>"
    content[:before] += "#{insert_space(6)}redirect_to root_path<br>"
    content[:before] += "#{insert_space(4)}else<br>"
    content[:after] +=  "#{insert_space(6)}render :new<br>"
    content[:after] +=  "#{insert_space(4)}end<br>"
  end

  # contents[:params_targets]をもとにストロングパラメーター取得メソッドを作成するメソッド
  def make_strong_parameter(contents)
    models = Model.includes(:columns).where(application_id: params[:application_id])
    target_model = '' # 初期化
    devise_name = '' # 初期化
    html = '' # 初期化
    contents[:params_targets].each do |target|
      models.each do |model|
        target_model = model if model.name == target
        devise_name = model.name if model.model_type_id == 5
      end

      # データ型によって配列を振り分ける。
      activehash_columns = [] # ActiveHashを使用している場合
      references_columns = [] # references型の場合
      normarl_columns = [] # 上記以外のデータ型の場合
      target_model.columns.each do |column|
        case column.data_type_id
        when 12 # references型のカラム
          references_columns << column.name
        when 13 # ActiveHashを参照するカラム
          activehash_columns << column.name
        else
          normarl_columns << column.name
        end
      end
      # 振り分けられた配列をもとにHTMLを作成
      html += "#{insert_space(2)}def #{target_model.name}_params<br>"
      html += "#{insert_space(4)}params.require(:#{target_model.name}).permit("
      first = true
      normarl_columns.each do |column|
        html += ', ' unless first
        html += ":#{column}"
        first = false
      end
      activehash_columns.each do |column|
        html += ', ' unless first
        html += ":#{column}_id"
        first = false
      end
      unless references_columns.empty?
        first = true
        html += ').merge('
        references_columns.each do |column|
          html += ', ' unless first
          html += if column != devise_name
                    "#{column}_id: params[:#{column}_id]"
                  else
                    "#{column}_id: current_user.id"
                  end
          first = false
        end
      end
      html += ")<br>#{insert_space(2)}end<br><br>"
    end
    html
  end

  # formで使用するインスタンス変数を取得するメソッドである、model_form_variableを作成するメソッド
  def make_model_form_variable(target, app_controllers, contents, links)
    app_controllers.each do |app_controller|
      next unless app_controller.name == target

      parent = app_controller.parent
      next if parent == ''

      contents[:model_form_variable] += "#{insert_space(4)}@#{parent} = #{parent.classify}.find(params[:#{parent}_id])"
      contents[:model_form_variable] += ' <- 自動生成' if links
      contents[:model_form_variable] += '<br>'
      make_model_form_variable(parent, app_controllers, contents, links)
    end
  end

  # before_action: model_form_variableを作成するメソッド
  def make_before_action_model_form_variable(contents)
    html = ''
    contents[:form_targets].each do |target|
      next unless contents["#{target}_form_actions".to_sym].length >= 2

      html += "#{insert_space(2)}before_action :#{target}_form_variable, only: ["
      first = true
      contents["#{target}_form_actions".to_sym].each do |element|
        html += ', ' unless first
        html += ":#{element}"
        first = false
      end
      html += ']<br>'
    end
    html
  end

  # before_action: get_comon_variableを作成するメソッド
  def make_before_action_common_variable(contents)
    html = ''
    common_actions = %w[common_variable1 common_variable2 common_variable3]
    common_actions.each do |action|
      next if contents[action.to_sym].nil?

      html += "#{insert_space(2)}before_action :#{action}"
      unless contents["#{action}_targets".to_sym].nil?
        first = true
        html += ', only: ['
        contents["#{action}_targets".to_sym].each do |target|
          html += ', ' unless first
          html += ":#{target.action_select}"
          first = false
        end
        html += ']'
      end
      html += '<br>'
    end
    html
  end

  # before_action: authenticate_user!のHTMLを作成するメソッド
  def before_action_authenticate_user(app_controller)
    html = "#{insert_space(2)}before_action :authenticate_user!"
    action_html = ', only: ['
    first = true
    action_count = 0
    actions = %w[index new create edit update destroy show]
    actions.each do |action|

app/views/app_actions/_code.html.erb
<div class="field">
  <b>
  <% case code.id %>
  <% when 1 %>
    <p>インスタンスを作成する。</p>
  <%  when 11 %>
    <p>一つのレコードを取得する。</p>
  <% when 21 %>
    <p>複数のレコードを取得する。</p>
  <% when 41 %>
    <p>複数のレコードと関連するテーブルを取得</p>
  <% when 61 %>
    <p>上記以外のレコード取得方法</p>
  <% when 81 %>
    <p>アソシエーションを利用してレコードを取得</p>
  <% when 91 %>
    <p>ページ遷移及びページ表示</p>
  <% when 97 %>
    <p>common_variable1-3の使用</p>
  <% end %>
  </b>
  <%= f.radio_button :action_code_id, code.id %><%== code.sample %>
  
  <% case code.id%>
  <% when 5 %>
    <p>
    <%== insert_space(4) %>@model = Model.new(model_params)<br>
    <%== insert_space(4) %>if @model.save<br>
    <%== insert_space(6) %>redirect_to root_path<br>
    <%== insert_space(4) %>else<br>
    <%== insert_space(6) %>他の登録アクションのコード<br>
    <%== insert_space(6) %>render :new<br>
    <%== insert_space(4) %>end
    </p>
  <% when 7 %>
    <p>
    <%== insert_space(4) %>if @model.update(model_params)<br>
    <%== insert_space(6) %>redirect_to root_path<br>
    <%== insert_space(4) %>else<br>
    <%== insert_space(6) %>他の登録アクションのコード<br>
    <%== insert_space(6) %>render :edit<br>
    <%== insert_space(4) %>end
    </p>
  <% when 6, 8 %>
    <p>
    <%== insert_space(4) %>上記のレイアウト(固定)を編集<br>
    <%== insert_space(4) %>redirect_to 条件式1<br>
    <%== insert_space(4) %>render 条件式2<br>
    </p>
  <% when 84 %>
    <p>
      <%== insert_space(4) %>
      アソシエーションを使用する場合、A_model名を条件式1に、B_model名を条件式2に入力してください
    </p>
  <% when 94 %>
    <p>
    上記を編集
    A_model -> 条件式1
    B_model -> 条件式2
    </p>
  <% when 99 %>
  <p>
    上記のcommon_variableを選択すると、登録したアクションをbefore_actionの適応先として登録できます。<br>
    この場合、選択した対象モデルは無効化されます。
  </p>
  <% end %>
</div>

app/views/app_actions/_form.html.erb
<%= form_with(model: [@application, @app_controller, @app_action], local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <h3>＜サンプルコードの選択＞</h3>
  <p>
    以下のサンプルから、アクションに登録したいコードを選択してください。<br>
    選択したサンプルにさらに設定を行います。
  </p>
  <%= render partial: "code", collection: ActionCode.all, locals: {f: f} %>


  <h3>＜コードの設定＞</h3>

  <p>アクションの登録先を選択してください。</p>
  <div class="field">
    <%= f.label :action_select, 'アクションの選択' %>
    <%= f.select(:action_select, make_selects(@app_controller)) %>
  </div>

  <p>
    対象となるモデルを選択してください。<br>
    上記サンプルコードの'model'が選択したモデル名に置き換えられます。
  </p>
  <div class="field">
    <%= f.label :target, '対象のモデル名を選択' %>
    <%= f.collection_select(:target, @models, :name, :name) %>
  </div>

  <p>
    サンプルコードの条件式の部分を置き換えたい場合、以下のフォームに内容を入力してください。<br>
    サンプル内に書かれている条件式と対応しないフォームに入力すると、内容は反映されません。
  </p>
  <div class="field">
    <%= f.label :input1, '条件式1' %>
    <%= f.text_field :input1 %>
  </div>
  <div class="field">
    <%= f.label :input2, '条件式2' %>
    <%= f.text_field :input2 %>
  </div>
  <div class="field">
    <%= f.label :input3, '条件式3' %>
    <%= f.text_field :input3 %>
  </div>
  <div class="actions">
    <%= f.submit "アクションの登録" %>
  </div>
<% end %>

app/views/app_actions/edit.html.erb
<h1><%= @app_controller.name %>コントローラーのアクション新規登録</h1>

<%= render partial: "form" %>
<%= render partial: "shared/link_index" %>

app/views/app_actions/index.html.erb
<h1><%= @app_controller.name %>のアクション一覧</h1>
<p>
コントローラーのコードを表示します。<br>
一部アクションは初期設定として登録されています。必要に応じ編集または削除してください。<br>
また、編集及び削除へのリンクなどはコード表示画面では非表示となります。
</p>
<h5>自動で作成されるメソッドについての補足説明</h5>
<div>
  コントローラーの登録内容により、一部メソッドが初期から作成されることがあります。<br>
  
  以下は作成されるメソッドに関する説明です。
</div>
<br>
<div>
  <b>＜model_params＞</b><br>
  DBへの保存の際に必要なストロングパラメーターを取得するためのメソッドです。<br>
  ストロングパラメーターが必要なアクションが登録されると自動生成されます。<br>
  実際には、'model'部分が対象のモデル名へ差し替えられます。
</div><br>
<div>
  <b>＜common_variable1-3＞</b><br>
  複数のアクションで共通する内容をbefore_actionで取得するメソッドです。<br>
  対象モデルが異なる場合に備え、三種類まで登録することが可能です。<br>
  初期設定では全てのアクションを対象にbefore_actionがで適応されています。<br>
  アクション登録時に、対象アクションと当メソッド名を選ぶことで、onlyにより適応アクションを限定できます。<br>
</div><br>
<div>
  <b>＜model_form_variable＞</b><br>
  登録されたコントローラーのネスト構造から、フォームに必要なインスタンス変数を取得するメソッドです。<br>
  登録内容から自動で生成されますが、このメソッドに任意のアクションを登録することもできます。<br>
  フォームに必要なインスタンス変数があれば、このメソッドにアクションを登録してください。
</div>
<br>
<%= link_to 'アクション新規作成へ',  new_application_app_controller_app_action_path %><br>
<%= link_to 'コード表示画面へ', application_app_controller_path(id: params[:app_controller_id]) %>
<br>

<h3><%= @app_controller.name %>コントローラーの内容</h3>
<%# 部分テンプレートを使用し、コントローラーのコードを表示します。また編集削除のリンクは表示されます。 %>
<%= render partial: "shared/controller", locals: {links: true} %>
<div>
  <b>※注意</b><br>
  初期設定の場合、redirect_toはroot_pathへ遷移する設定となっています。<br>
  必要に応じ、実装時に変更、またはレイアウト(編集)へ設定を変更してください。
</div>
<br>
<%= link_to 'アクション新規作成へ',  new_application_app_controller_app_action_path %><br>
<%= link_to 'コード表示画面へ', application_app_controller_path(id: params[:app_controller_id]) %>
<%= render partial: "shared/link_index" %>

app/views/app_actions/new.html.erb
<h1><%= @app_controller.name %>コントローラーのアクション新規登録</h1>

<%= render partial: "form" %>
<%= render partial: "shared/link_index" %>