config/routes.rb
Rails.application.routes.draw do
  root to: 'applications#index'
  devise_for :users
  resources :applications do
    resources :gemfiles, only: [:index, :new, :create, :edit, :update, :show]
    resources :models do
      resources :columns, only: [:new, :create, :edit, :update, :destroy] do
        resources :options, only: [:new, :create]
      end
    end
    resources :app_controllers do
      resources :app_actions, only: [:index, :new, :create, :edit, :update, :destroy]
    end
  end
end

app/views/shared/_column_form.html.erb
<%= form_with(model: [application, model, column], local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :name, 'カラム名' %>
    <%= f.text_field :name, autofocus: true, placeholder: 'nickname' %><br>
    保存するカラムの名前を設定します。
  </div>
  <br>
  <% if @application.gemfile.rails_i18n %>
    <div class="field">
      <%= f.label :name_ja, '日本語表記' %>
      <%= f.text_field :name_ja, placeholder: 'ニックネーム' %><br>
      エラー文を翻訳する際の表示を設定します。
    </div>
  <% end %>
  <br>
  <br>
  <div class="field">
    <div class="info">
      以下よりカラムのデータ型を選択してください
    </div>
    <div class="letter-field">
      <p><%= f.radio_button :data_type_id, 1 %><%= DataType.find(1)[:type] %>型</p>  
      <p><%= f.radio_button :data_type_id, 2 %><%= DataType.find(2)[:type] %>型</p>
    </div>
    <div class="number-field">
      <p><%= f.radio_button :data_type_id, 3 %><%= DataType.find(3)[:type] %>型</p>  
      <p><%= f.radio_button :data_type_id, 4 %><%= DataType.find(4)[:type] %>型</p>
      <p><%= f.radio_button :data_type_id, 5 %><%= DataType.find(5)[:type] %>型</p>
    </div>
    <div class="date-field">
      <p><%= f.radio_button :data_type_id, 6 %><%= DataType.find(6)[:type] %>型</p>  
      <p><%= f.radio_button :data_type_id, 7 %><%= DataType.find(7)[:type] %>型</p>
      <p><%= f.radio_button :data_type_id, 8 %><%= DataType.find(8)[:type] %>型</p>
    </div>
    <div class="boolean-field">
      <p><%= f.radio_button :data_type_id, 11 %><%= DataType.find(11)[:type] %>型</p>  
    </div>
  </div>

  <div class="field">
    <%= f.check_box :must_exist ,{}, true, false %>
    <%= f.label :must_exist, '空欄を禁止する。' %>
  </div>

  <div class="field">
    <%= f.check_box :unique ,{}, true, false %>
    <%= f.label :unique, 'テーブル内での重複を禁止する' %>
  </div>

  <div class="actions">
    <%= f.submit "オプション設定へ" %>
  </div>
<% end %>

app/views/shared/_controller.html.erb
<% contents = make_controller_array(@app_actions) %>
<div class="code-field">
  <div class="code-tab">
    <%= image_tag "ruby_icon.png", class: "code-icon", size: "16x16", alt: "Ruby" %>
    <%= "20XXXX...._create_#{@app_controller.name.tableize}.rb" %>
    <%= image_tag "cross_icon.png", class: "code-icon", size: "16x16", alt: "Ruby" %>
  </div>
  <div class="code-route">
    db > migrate > 
    <%= image_tag "ruby_icon.png", class: "code-icon", size: "12x12", alt: "Ruby" %>
    <%= "20XXXX...._create_#{@app_controller.name.tableize}.rb" %>
  </div>
  <div class="code-contents">
    class <%= @app_controller.name.pluralize.camelize %>Controller < ApplicationController<br>
    <%== before_action_authenticate_user(@app_controller) %>
    <%== make_before_action_model_form_variable(contents) %>
    <%== make_before_action_common_variable(contents) %>
    <%== "#{insert_space(2)}※ 上記のbefore_actionは自動生成<br>" if links %>
    <br>

    <%# 基本の７つのアクションに関する記載を行う。 %>
    <% seven_actions = %w[index new create edit update destroy show] %>
    <% seven_actions.each do |action| %>
      <% if @app_controller["#{action}_select"] >= 2 %>
      
        <%== "#{insert_space(2)}def #{action}<br>"  %>
        <% contents[action.to_sym].each do |app_action| %>
          <% content = {first: '', before: '', main: '', after: ''} %>
          <% make_action_code_remake(app_action, links, content) %>

          <%== content[:first] %>
          <%== content[:before] %>
          <%== content[:main] %>
          <% if links %>
            <%= link_to '編集', edit_application_app_controller_app_action_path(id: app_action), class: "links" %>
            <%= link_to '削除', application_app_controller_app_action_path(id: app_action), method: :delete, class: "links" %>
          <% end %>
          <br>
          <%# レイアウトを使用する場合、create/updateのためmodel_form_variableの内容に合わせて挿入が必要。 %>
          <% if [1, 2, 3, 4, 5, 6, 7, 8].include?(app_action.action_code_id) && !contents["#{app_action.target}_form_actions".to_sym].nil? %>
            <% if contents["#{app_action.target}_form_actions".to_sym].length == 1 %>
              <% contents[:model_form_variable] = '' %>
              <% make_model_form_variable(app_action.target, @app_controllers, contents, links) %>
              <%== contents[:model_form_variable] %>
            <% elsif [5, 6, 7, 8].include?(app_action.action_code_id) && contents["#{app_action.target}_form_actions".to_sym].length >= 2 %>
              <%== "#{insert_space(6)}#{app_action.target}_form_variable" %>
              <%== ' <- 自動生成' if links %>
              <%== '<br>' %>
            <% end %>
          <% end %>
          <%#/ レイアウトを使用する場合の挿入%>

          <%== content[:after] %>
        <% end %>
        <%== "#{insert_space(2)}end<br><br>"  %>
      <% end %>
    <% end %>

    <%== "#{insert_space(2)}private<br><br>" %>

    <%# model_params: ストロングパラメーター取得メソッド %>
    <%== make_strong_parameter(contents) %>
    
    <%# common_variable1-3: 各アクションの共通となるインスタンス変数を取得するメソッド %>
    <% common_actions = %w[common_variable1 common_variable2 common_variable3] %>
    <% common_actions.each do |action| %>
      <% unless contents[action.to_sym].nil? %>
        <%== "#{insert_space(2)}def #{action}<br>"  %>
        <% contents[action.to_sym].each do |app_action| %>
          <% content = {first: '', before: '', main: '', after: ''} %>
          <% make_action_code_remake(app_action, links, content) %>
          <%== content[:first] %>
          <%== content[:before] %>
          <%== content[:main] %>
          <% if links %>
            <%= link_to '編集', edit_application_app_controller_app_action_path(id: app_action), class: "links" %>
            <%= link_to '削除', application_app_controller_app_action_path(id: app_action), method: :delete, class: "links" %>
          <% end %>
          <br>
          <%== content[:after] %>
        <% end %>
        <%== "#{insert_space(2)}end<br>" %>
        <% if links && !contents["#{action}_targets".to_sym].nil? %>
          <%== "#{insert_space(2)}＜#{action}を適応しているアクション＞<br>" %>
          <% contents["#{action}_targets".to_sym].each do |target| %>
            <%== "#{insert_space(4)}#{target.action_select}" %>
            <%= link_to '編集', edit_application_app_controller_app_action_path(id: target), class: "links" %>
            <%= link_to '削除', application_app_controller_app_action_path(id: target), method: :delete, class: "links" %>
            <br>
          <% end %>
        <% end %><br>
      <% end %>
    <% end %>


    <%# model_form_variable: フォームのために必要なインスタンス変数を取得するメソッドを作成 %>
    <% contents[:params_targets].each do |target| %>
      <% next unless contents["#{target}_form_actions".to_sym].length >= 2 %>

      <% contents[:model_form_variable] = '' %>
      <% make_model_form_variable(target, @app_controllers, contents, links) %>
      
      <%== "#{insert_space(2)}def #{target}_form_variable<br>" %>
      <%== contents[:model_form_variable] %>
      <% unless contents["#{target}_form_variable".to_sym].nil? %>
        <% contents["#{target}_form_variable".to_sym].each do |app_action| %>
          <% content = {first: '', before: '', main: '', after: ''} %>
          <% make_action_code_remake(app_action, links, content) %>

          <%== content[:first] %>
          <%== content[:before] %>
          <%== content[:main] %>
          <% if links %>
            <%= link_to '編集', edit_application_app_controller_app_action_path(id: app_action), class: "links" %>
            <%= link_to '削除', application_app_controller_app_action_path(id: app_action), method: :delete, class: "links" %>
            <br>
          <% end %>
        <% end %>
      <% end %>
      <%== "#{insert_space(2)}end<br><br>" %>
    <% end %>
  end
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_link_index.html.erb
<div>
  <%= link_to 'モデル一覧へ', application_models_path %><br>
  <%= link_to 'コントローラー一覧へ', application_app_controllers_path %><br>
  <%= link_to 'アプリケーション詳細へ戻る', application_path(params[:application_id]) %><br>
  <%= link_to 'トップページへ戻る', root_path %>
</div>

app/views/shared/_model_form.html.erb
<%= form_with(model: [application,  model], local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, placeholder: 'itemなど単数形' %>
    </div>

     <div class="field">
      <p>作成するモデルの種類を選択してください</p>
      <p><%= f.radio_button :model_type_id, 1, checked: true %>一般的なモデルの登録</p>  
      <% if application.gemfile.active_hash %>
        <p><%= f.radio_button :model_type_id, 2 %>ActiveHashの登録</p>
      <% end %>
      <p><%= f.radio_button :model_type_id, 3 %>中間テーブルの登録</p>
      <p><%= f.radio_button :model_type_id, 4 %>Formオブジェクトパターンの登録</p>
    </div>

    <p>
      一般的なモデルを作成する場合、以下のチェック項目を確認してください。<br>
      該当する場合はチェックを入れてください。
    </p>
    <div class="field">
      <%= f.check_box :not_only ,{}, false, true %>
      <%= f.label :not_only, '親モデルに対して一対一の関係である has_one' %><br>
      親モデルに対して一対多、または親モデルが存在しない場合はチェックを外したまま登録してください
    </div>

    <div class="field">
      <%= f.check_box :attached_image ,{}, true, false %>
      <%= f.label :attached_image, '画像データを紐付ける対象となる' %><br>
      Imagemagickを使用し、当モデルに対して画像を紐づける場合はチェックを入れてください
    </div>

    <div class="actions">
      <%= f.submit "カラム登録へ" %>
    </div>
  <% end %>

<%# render partial: "shared/model_form", locals: {application: @application, model: @model} %>

app/views/shared/_related_models.html.erb
<div class="columns-index">
  <h2>＜<%= model.name %>のカラム一覧＞</h2>
  <% model.columns.each do |column| %>
    <%= column.name %> -> <%= column.data_type.type %>型 -> option:
    <%= '空欄禁止' if column.must_exist %> <%= '重複禁止' if column.unique %>
    <% column.options.each do |option| %>
      <%= option.option_type.info %>  
    <% end %><br>
    <%= link_to 'カラムを編集', edit_application_model_column_path(id: column) %> 
    <%= link_to 'カラムを削除', application_model_column_path(id: column), method: :delete %><br>
  <% end %><br>
  <% if model.model_type_id == 5 %>
    email -> string -> option: 空欄禁止 重複禁止<br>
    encrypted_password -> string -> 空欄禁止 
  <% elsif model.columns.length == 0 %>
    まだカラムは登録されていません
  <% end %><br>
</div>

<%# render partial: "shared/related_models", locals: {model: @model} %>